server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/foodapp
    username: postgres
    password: Pch1286

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    mongodb:
      uri: mongodb://localhost:27017/foodmenu

  server:
    port: 8080